; Ensō — Ambient Sound Simulator for M5Stack Cardputer ADV
; Build with PlatformIO (VSCode). After a successful build you will find:
;   .pio/build/m5stack-cardputer-adv/firmware.bin  -> for Launcher FW
;   .pio/build/m5stack-cardputer-adv/merge.bin     -> for M5Burner (bootloader+partitions+app merged)

[env:m5stack-cardputer-adv]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 921600
upload_speed = 921600

board_build.partitions = default_8MB.csv
board_build.flash_mode = dio
board_upload.flash_size = 8MB

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -O2

lib_deps =
    m5stack/M5Cardputer
    m5stack/M5Unified
    m5stack/M5GFX
    bblanchon/ArduinoJson@^7.0.0
    adafruit/Adafruit NeoPixel@^1.12.0

extra_scripts = post:merge_bin.py
